on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  DEBUG_TYPE: Debug

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.DEBUG_TYPE}} -G Ninja

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.DEBUG_TYPE}} 

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ctest -C ${{env.DEBUG_TYPE}}

